server: 
  port: 7001
  context-path: /
spring:
  application:
    name: approve-config
  cloud: 
    config: 
      server: 
        git: 
          password: aerbeisi163
          searchPaths: cloud-config-repo,application, custom, log, database
          uri: "https://github.com/scj2085/approve-config.git"
          username: scj2085@163.com
#    bus:
#      destination: bus
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: "http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/" #注册到集群中-
management:
  security:
    enabled: false
      
# 问题：为何config-server resources目录下配置多个环境，在repo中配置就行了，可使用启动命令指定使用哪个环境     