server.port: 9998
spring:
  cloud:
    stream:
      defaultBinder: rabbit1 #使用RabbitMQ设置默认绑定器
      bindings:
        testChannel: #输入通道名称
          binder: rabbit1 #绑定器标识符
 #         group: Service-A #指定该应用实例都属于Service-A消费组，当部署一个服务多个实例时，在同一个组的实例，只有一个实例消费，以伦轮询的方式进行接收和输出
        testChannel2:
          binder: rabbit1 #绑定器标识符
        testChannel3: #输出通道名
          binder: rabbit1 #绑定器标识符
          content-type: application/json #指定传递参数类型
      binders: #自定义绑定器配置
        rabbit1: #绑定器标识符
          type: rabbit #绑定器类型
          environment: #设置绑定器属性
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: springcloud
                password: 123456
 #       rabbit2:
 #         type: rabbit
 #         environment:
 #           spring:
 #             rabbitmq:
 #               host: 127.0.0.1
 #               port: 5673
 #               username: springcloud
 #               password: 123456 